### ISSUE TITLE
Assign numpy implementation always returning float64

### ISSUE THREAD

**Issue by ianspektor** [google/temporian#47]
Assign numpy implementation always returning float64.

_Originally posted by @ianspektor in https://github.com/google/temporian/pull/43#discussion_r1142372481_

**Comment by diegomarvid** [comment]
This behavior is because we fill with `np.nan` when the exact timestamp is not matched. We could improve this to only convert to float in that specific scenario. However, as we discussed in yesterday's meeting, if we change our current assign implementation to `assign (exact timestamps)` + `resample`, then this behavior will not happen. We won't need to fill with np.nan where timestamps don't match and therefore we can set the dtype to int for example.
